import { CommonModule } from '@angular/common';
import { Component, DestroyRef, ElementRef, OnInit, ViewChild, computed, inject, signal } from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, Router, RouterModule } from '@angular/router';
import { UserOnlineState } from '@sendbird/chat';
import { BaseMessage, UserMessage } from '@sendbird/chat/message';
import { GroupChannel, GroupChannelHandler, Member } from '@sendbird/chat/groupChannel';
import { combineLatest, firstValueFrom } from 'rxjs';
import { AuthStateService } from '../../../../auth/services/auth-state.service';
import { UserService } from '../../../../auth/services/user.service';
import { SendbirdService } from '../../../services/sendbird.service';

type ChatMessageDetails = BaseMessage & {
  reqId?: string;
  sender?: {
    userId?: string;
    nickname?: string;
    profileUrl?: string;
  };
};

type MessageVisibility = {
  label: string;
  state: 'delivered' | 'seen';
};

type PendingChatImage = {
  file: File;
  previewUrl: string;
};

type TranslationDisplayMode = 'original' | 'translated';

@Component({
  selector: 'app-chat-component',
  templateUrl: './chat-component.html',
  styleUrls: ['./chat-component.scss'],
  imports: [CommonModule, FormsModule, RouterModule],
})
export class ChatComponent implements OnInit {
  @ViewChild('messageList')
  private messageListRef?: ElementRef<HTMLDivElement>;

  private readonly destroyRef = inject(DestroyRef);
  private readonly route = inject(ActivatedRoute);
  private readonly router = inject(Router);
  private readonly authState = inject(AuthStateService);
  private readonly userService = inject(UserService);
  private readonly sbService = inject(SendbirdService);

  protected readonly channels = signal<GroupChannel[]>([]);
  protected readonly selectedChannel = signal<GroupChannel | null>(null);
  protected readonly messages = signal<BaseMessage[]>([]);
  protected readonly isBootstrapping = signal(true);
  protected readonly isLoadingMessages = signal(false);
  protected readonly isSending = signal(false);
  protected readonly error = signal<string | null>(null);
  protected readonly imageError = signal<string | null>(null);
  protected readonly activeRecipientId = signal<string | null>(null);
  protected readonly recipientChatLanguage = signal<string | null>(null);
  protected readonly starterContextLabel = signal<string | null>(null);
  protected readonly typingUsers = signal<Member[]>([]);
  protected readonly selectedImages = signal<PendingChatImage[]>([]);
  protected readonly translationDisplayModes = signal<Record<string, TranslationDisplayMode>>({});

  protected draftMessage = '';
  protected readonly maxSelectedImages = 6;

  private readonly handlerKey = `kickoff-chat-${Math.random().toString(36).slice(2)}`;
  private readonly timeFormatter = new Intl.DateTimeFormat(undefined, {
    hour: 'numeric',
    minute: '2-digit',
  });
  private readonly maxImageSizeBytes = 8 * 1024 * 1024;
  private bootstrapVersion = 0;
  private messageLoadVersion = 0;
  private hasRealtimeHandler = false;
  private bootstrappedUserId: string | null = null;
  private typingTimeoutId: ReturnType<typeof setTimeout> | null = null;
  private typingChannelUrl: string | null = null;
  private hasActiveTypingSignal = false;
  private autoGeneratedDraft: string | null = null;
  private readonly translationRequestKeys = new Set<string>();

  protected readonly activeTypingName = computed(() => {
    const activeTypingUser = this.typingUsers()[0];
    return activeTypingUser?.nickname?.trim() || activeTypingUser?.userId || null;
  });

  constructor() {
    this.destroyRef.onDestroy(() => {
      void this.stopTypingIndicator();
      this.revokeImagePreviews(this.selectedImages());
      this.sbService.removeGroupChannelHandler(this.handlerKey);
    });
  }

  ngOnInit(): void {
    combineLatest([this.route.paramMap, this.route.queryParamMap])
      .pipe(
        takeUntilDestroyed(this.destroyRef),
      )
      .subscribe(([paramMap, queryParamMap]) => {
        const recipientId = paramMap.get('userId');
        const starterType = queryParamMap.get('starter');
        const projectName = queryParamMap.get('projectName');
        const starterDraft = this.resolveStarterDraft(starterType, projectName);

        this.applyRouteStarter(starterDraft, starterType === 'project-owner' ? projectName : null);
        void this.bootstrapChat(recipientId);
      });
  }

  protected get currentUserId(): string | null {
    return this.authState.currentUser()?.idP ?? null;
  }

  protected get currentUserPreferredChatLanguage(): string | null {
    return this.normalizeLanguage(this.authState.currentUser()?.preferredChatLanguage);
  }

  protected get chatTranslationSummary(): string | null {
    const preferredLanguageLabel = this.chatLanguageLabel(this.currentUserPreferredChatLanguage);
    if (!preferredLanguageLabel) {
      return null;
    }

    const readingMode = this.currentUserPrefersOriginalText
      ? 'Original text appears first.'
      : 'Translated text appears first.';

    return `Incoming messages translate to ${preferredLanguageLabel} when available. ${readingMode}`;
  }

  protected get hasChannels(): boolean {
    return this.channels().length > 0;
  }

  protected trackChannel(_index: number, channel: GroupChannel): string {
    return channel.url;
  }

  protected trackMessage(_index: number, message: BaseMessage): string {
    return message.messageId > 0
      ? `message-${message.messageId}`
      : `request-${this.messageDetails(message).reqId ?? _index}`;
  }

  protected async openChannel(channel: GroupChannel): Promise<void> {
    const otherMember = this.otherMember(channel);

    if (!otherMember?.userId || otherMember.userId === this.currentUserId) {
      await this.router.navigate(['/chat']);
      return;
    }

    await this.router.navigate(['/chat', otherMember.userId]);
  }

  protected async goToInbox(): Promise<void> {
    await this.router.navigate(['/chat']);
  }

  protected async retry(): Promise<void> {
    await this.bootstrapChat(this.activeRecipientId());
  }

  protected async sendMessage(): Promise<void> {
    const activeChannel = this.selectedChannel();
    const content = this.draftMessage.trim();
    const selectedImages = this.selectedImages();

    if (!activeChannel || (!content && selectedImages.length === 0) || this.isSending()) {
      return;
    }

    const otherMember = this.otherMember(activeChannel);
    if (!otherMember?.userId || otherMember.userId === this.currentUserId) {
      this.error.set('You cannot send messages to yourself.');
      return;
    }

    this.isSending.set(true);
    this.error.set(null);
    this.imageError.set(null);
    this.clearStarterContext();
    await this.stopTypingIndicator(activeChannel.url);

    let pendingText = content;
    let pendingImages = [...selectedImages];

    try {
      if (content) {
        const message = await this.sbService.sendMessage(
          activeChannel.url,
          content,
          this.translationTargetLanguages,
        );
        this.messages.update(existingMessages => this.upsertMessage(existingMessages, message));
        this.scrollMessagesToBottom();
        pendingText = '';
      }

      for (const image of selectedImages) {
        const imageMessage = await this.sbService.sendImageMessage(activeChannel.url, image.file);
        this.messages.update(existingMessages => this.upsertMessage(existingMessages, imageMessage));
        this.scrollMessagesToBottom();
        pendingImages = pendingImages.filter(candidate => candidate.previewUrl !== image.previewUrl);
      }

      this.revokeImagePreviews(selectedImages);
      this.selectedImages.set([]);
      this.draftMessage = '';

      const refreshedChannel = await this.sbService.getChannel(activeChannel.url);
      this.selectedChannel.set(refreshedChannel);
      this.channels.update(existingChannels => this.sortChannels(this.upsertChannel(existingChannels, refreshedChannel)));
      await this.sbService.markAsRead(refreshedChannel.url);
    } catch (error) {
      console.error(error);
      this.draftMessage = pendingText;
      this.selectedImages.set(pendingImages);

      const sentImages = selectedImages.filter(image =>
        !pendingImages.some(candidate => candidate.previewUrl === image.previewUrl),
      );

      if (sentImages.length > 0) {
        this.revokeImagePreviews(sentImages);
      }

      this.error.set(sentImages.length > 0 || pendingText !== content
        ? 'Part of your message was sent, but some images failed to upload.'
        : 'Your message could not be sent. Please try again.');
    } finally {
      this.isSending.set(false);
    }
  }

  protected async handleComposerKeydown(event: KeyboardEvent): Promise<void> {
    if (event.key !== 'Enter' || event.shiftKey || event.isComposing) {
      return;
    }

    event.preventDefault();
    await this.sendMessage();
  }

  protected handleDraftChange(): void {
    const activeChannel = this.selectedChannel();

    if (!activeChannel || !this.draftMessage.trim()) {
      void this.stopTypingIndicator();
      return;
    }

    void this.signalTyping(activeChannel.url);
  }

  protected handleComposerBlur(): void {
    void this.stopTypingIndicator();
  }

  protected onImagesSelected(event: Event): void {
    const input = event.target as HTMLInputElement;
    const files = Array.from(input.files ?? []);

    if (files.length === 0) {
      return;
    }

    const remainingSlots = Math.max(0, this.maxSelectedImages - this.selectedImages().length);
    if (remainingSlots <= 0) {
      this.imageError.set(`You can attach up to ${this.maxSelectedImages} images.`);
      input.value = '';
      return;
    }

    const imagesToAdd = files.slice(0, remainingSlots);
    const oversizeFile = imagesToAdd.find(file => file.size > this.maxImageSizeBytes);
    if (oversizeFile) {
      this.imageError.set('Each image must be 8MB or smaller.');
      input.value = '';
      return;
    }

    const invalidFile = imagesToAdd.find(file => !file.type.startsWith('image/'));
    if (invalidFile) {
      this.imageError.set('Only image files can be added here.');
      input.value = '';
      return;
    }

    this.imageError.set(null);
    this.selectedImages.update(existingImages => ([
      ...existingImages,
      ...imagesToAdd.map(file => ({
        file,
        previewUrl: URL.createObjectURL(file),
      })),
    ]));
    input.value = '';
  }

  protected removeSelectedImage(index: number): void {
    if (this.isSending()) {
      return;
    }

    const imageToRemove = this.selectedImages()[index];
    if (!imageToRemove) {
      return;
    }

    URL.revokeObjectURL(imageToRemove.previewUrl);
    this.selectedImages.update(images => images.filter((_, currentIndex) => currentIndex !== index));
    this.imageError.set(null);
  }

  protected channelTitle(channel: GroupChannel): string {
    return this.otherMember(channel)?.nickname?.trim() || this.otherMember(channel)?.userId || 'Direct chat';
  }

  protected channelPreview(channel: GroupChannel): string {
    const lastMessage = channel.lastMessage;

    if (!lastMessage) {
      return 'Start the conversation';
    }

    if (lastMessage.isFileMessage()) {
      return lastMessage.message?.trim() || 'Shared an image';
    }

    return this.messageTranslation(lastMessage) || lastMessage.message?.trim() || 'Start the conversation';
  }

  protected channelPresence(channel: GroupChannel): string {
    return this.memberPresence(this.otherMember(channel));
  }

  protected channelPresenceLive(channel: GroupChannel): boolean {
    return this.isMemberLive(this.otherMember(channel));
  }

  protected channelTimestamp(channel: GroupChannel): number {
    return channel.lastMessage?.createdAt || channel.createdAt || Date.now();
  }

  protected channelUnreadCount(channel: GroupChannel): number {
    return channel.unreadMessageCount ?? 0;
  }

  protected channelAvatar(channel: GroupChannel): string | null {
    return this.otherMember(channel)?.profileUrl || null;
  }

  protected channelInitials(channel: GroupChannel): string {
    return this.initials(this.channelTitle(channel));
  }

  protected participantProfileLink(channel: GroupChannel | null): string[] | null {
    const otherMember = this.otherMember(channel);
    return otherMember?.userId ? ['/profile', otherMember.userId] : null;
  }

  protected participantSummary(channel: GroupChannel | null): string {
    if (!channel) {
      return 'Select a conversation to read and send messages.';
    }

    const participant = this.otherMember(channel);
    if (participant?.nickname?.trim()) {
      return `Direct conversation with ${participant.nickname}.`;
    }

    return 'Direct conversation inside KickOff.';
  }

  protected participantPresence(channel: GroupChannel | null): string {
    const activeTypingName = this.activeTypingName();
    if (activeTypingName) {
      return `${activeTypingName} is typing...`;
    }

    return this.memberPresence(this.otherMember(channel));
  }

  protected participantPresenceLive(channel: GroupChannel | null): boolean {
    const participant = this.otherMember(channel);

    return this.typingUsers().length > 0 || participant?.connectionStatus === UserOnlineState.ONLINE;
  }

  protected isOwnMessage(message: BaseMessage): boolean {
    return this.messageDetails(message).sender?.userId === this.currentUserId;
  }

  protected messageSender(message: BaseMessage): string {
    const { sender } = this.messageDetails(message);

    if (sender) {
      return sender.nickname?.trim() || sender.userId || 'KickOff member';
    }

    return 'KickOff';
  }

  protected messageAvatar(message: BaseMessage): string | null {
    return this.messageDetails(message).sender?.profileUrl || null;
  }

  protected messageInitials(message: BaseMessage): string {
    return this.initials(this.messageSender(message));
  }

  protected messageText(message: BaseMessage): string {
    if (message.isFileMessage()) {
      return message.message?.trim() || 'Shared an image.';
    }

    const originalText = message.message?.trim() || 'Shared an update in this conversation.';
    if (this.shouldShowOriginalMessage(message)) {
      return originalText;
    }

    return this.messageTranslation(message) ?? originalText;
  }

  protected messageCaption(message: BaseMessage): string | null {
    const caption = message.message?.trim();
    return caption ? caption : null;
  }

  protected imageMessageUrl(message: BaseMessage): string | null {
    if (!message.isFileMessage() || !message.type.startsWith('image/')) {
      return null;
    }

    return message.thumbnails[0]?.url || message.url;
  }

  protected imageMessageAlt(message: BaseMessage): string {
    if (!message.isFileMessage()) {
      return 'Shared image';
    }

    return this.messageCaption(message) || message.name || 'Shared image';
  }

  protected messageVisibility(message: BaseMessage): MessageVisibility | null {
    const activeChannel = this.selectedChannel();

    if (!activeChannel || !this.isOwnMessage(message) || !this.isLatestOwnMessage(message)) {
      return null;
    }

    const unreadMembers = activeChannel
      .getUnreadMembers(message)
      .filter(member => member.userId !== this.currentUserId);

    if (unreadMembers.length === 0) {
      const participant = this.otherMember(activeChannel);
      const readAt = participant?.userId
        ? activeChannel.getReadStatus()?.[participant.userId]?.readAt ?? null
        : null;

      return {
        state: 'seen',
        label: readAt && readAt >= message.createdAt
          ? `Seen ${this.timeFormatter.format(readAt)}`
          : 'Seen',
      };
    }

    return {
      state: 'delivered',
      label: 'Delivered',
    };
  }

  protected canToggleMessageTranslation(message: BaseMessage): boolean {
    return !!this.messageTranslation(message);
  }

  protected toggleMessageTranslation(message: BaseMessage): void {
    const messageKey = this.messageKey(message);
    const nextMode: TranslationDisplayMode = this.shouldShowOriginalMessage(message)
      ? 'translated'
      : 'original';

    this.translationDisplayModes.update(modes => ({
      ...modes,
      [messageKey]: nextMode,
    }));
  }

  protected translationToggleLabel(message: BaseMessage): string {
    return this.shouldShowOriginalMessage(message)
      ? 'Show translation'
      : 'Show original';
  }

  protected isShowingTranslatedMessage(message: BaseMessage): boolean {
    return this.canToggleMessageTranslation(message) && !this.shouldShowOriginalMessage(message);
  }

  private async bootstrapChat(recipientId: string | null): Promise<void> {
    const currentUserId = this.currentUserId;
    const version = ++this.bootstrapVersion;
    const canReuseInbox = !!currentUserId && this.bootstrappedUserId === currentUserId && this.hasRealtimeHandler;

    this.activeRecipientId.set(recipientId);
    this.error.set(null);
    this.isBootstrapping.set(!canReuseInbox);
    this.typingUsers.set([]);

    if (!currentUserId) {
      this.bootstrappedUserId = null;
      this.resetChatState();
      this.error.set('You need to be signed in to use chat.');
      this.isBootstrapping.set(false);
      return;
    }

    if (recipientId && recipientId === currentUserId) {
      await this.router.navigate(['/chat']);
      return;
    }

    try {
      await this.sbService.connect(currentUserId, this.currentUserPreferredLanguages);

      if (version !== this.bootstrapVersion) {
        return;
      }

      let channels = this.channels();

      if (!canReuseInbox) {
        this.registerRealtimeHandler();

        channels = this.normalizeChannels(await this.sbService.getChannels({ includeEmpty: true, limit: 30 }));

        if (version !== this.bootstrapVersion) {
          return;
        }

        this.channels.set(channels);
        this.bootstrappedUserId = currentUserId;
      } else {
        channels = this.normalizeChannels(channels);
        this.channels.set(channels);
      }

      if (recipientId) {
        const existingChannel = this.findChannelByMember(channels, recipientId);

        if (existingChannel) {
          await this.loadChannel(existingChannel);
          return;
        }

        const directChannel = await this.sbService.createDirectChannel(currentUserId, recipientId);

        if (version !== this.bootstrapVersion) {
          return;
        }

        channels = this.normalizeChannels(this.upsertChannel(channels, directChannel));
        this.channels.set(channels);
        await this.loadChannel(directChannel);
        return;
      }

      const nextChannel = this.resolveSelectedChannel(channels);

      if (!nextChannel) {
        this.clearSelectedImages();
        this.selectedChannel.set(null);
        this.messages.set([]);
        this.recipientChatLanguage.set(null);
        return;
      }

      await this.loadChannel(nextChannel);
    } catch (error) {
      console.error('Failed to bootstrap chat.', {
        currentUserId,
        recipientId,
        error,
      });

      if (version !== this.bootstrapVersion) {
        return;
      }

      if (!canReuseInbox) {
        this.bootstrappedUserId = null;
        this.resetChatState();
      }

      this.error.set('We could not open chat right now. Please try again in a moment.');
    } finally {
      if (version === this.bootstrapVersion) {
        this.isBootstrapping.set(false);
      }
    }
  }

  private async loadChannel(channel: GroupChannel): Promise<void> {
    const version = ++this.messageLoadVersion;
    const previousChannelUrl = this.selectedChannel()?.url;
    await this.stopTypingIndicator();

    if (previousChannelUrl && previousChannelUrl !== channel.url) {
      this.clearSelectedImages();
      this.translationDisplayModes.set({});
    }

    if (!this.isMessageableChannel(channel)) {
      this.selectedChannel.set(null);
      this.messages.set([]);
      this.typingUsers.set([]);
      this.recipientChatLanguage.set(null);
      this.error.set('You cannot open a chat with yourself.');
      return;
    }

    this.selectedChannel.set(channel);
    this.isLoadingMessages.set(true);
    this.error.set(null);

    try {
      const [freshChannel, messages] = await Promise.all([
        this.sbService.getChannel(channel.url),
        this.sbService.getMessages(channel.url),
      ]);

      if (version !== this.messageLoadVersion) {
        return;
      }

      this.selectedChannel.set(freshChannel);
      this.messages.set(messages);
      await this.loadRecipientChatLanguage(freshChannel, version);
      this.updateTypingUsers(freshChannel);
      this.channels.update(existingChannels => this.normalizeChannels(this.upsertChannel(existingChannels, freshChannel)));
      await this.sbService.markAsRead(freshChannel.url);
      this.scrollMessagesToBottom();
      void this.ensureMessageTranslations(freshChannel.url, messages);
    } catch (error) {
      console.error(error);

      if (version !== this.messageLoadVersion) {
        return;
      }

      this.messages.set([]);
      this.recipientChatLanguage.set(null);
      this.error.set('We could not load this conversation.');
    } finally {
      if (version === this.messageLoadVersion) {
        this.isLoadingMessages.set(false);
      }
    }
  }

  private registerRealtimeHandler(): void {
    if (this.hasRealtimeHandler) {
      return;
    }

    this.sbService.addGroupChannelHandler(
      this.handlerKey,
      new GroupChannelHandler({
        onChannelChanged: channel => {
          const groupChannel = channel as GroupChannel;
          this.channels.update(existingChannels => this.normalizeChannels(this.upsertChannel(existingChannels, groupChannel)));

          if (this.selectedChannel()?.url === groupChannel.url) {
            if (this.isMessageableChannel(groupChannel)) {
              this.selectedChannel.set(groupChannel);
              this.updateTypingUsers(groupChannel);
            } else {
              this.clearSelectedImages();
              this.selectedChannel.set(null);
              this.messages.set([]);
              this.recipientChatLanguage.set(null);
              this.translationDisplayModes.set({});
              this.typingUsers.set([]);
            }
          }
        },
        onChannelDeleted: channelUrl => {
          this.channels.update(existingChannels => existingChannels.filter(channel => channel.url !== channelUrl));

          if (this.selectedChannel()?.url === channelUrl) {
            this.clearSelectedImages();
            this.selectedChannel.set(null);
            this.messages.set([]);
            this.recipientChatLanguage.set(null);
            this.translationDisplayModes.set({});
            this.typingUsers.set([]);
          }
        },
        onMessageReceived: (channel, message) => {
          const groupChannel = channel as GroupChannel;
          this.channels.update(existingChannels => this.normalizeChannels(this.upsertChannel(existingChannels, groupChannel)));

          if (this.selectedChannel()?.url === groupChannel.url) {
            this.selectedChannel.set(groupChannel);
            this.updateTypingUsers(groupChannel);
            this.messages.update(existingMessages => this.upsertMessage(existingMessages, message));
            void this.sbService.markAsRead(groupChannel.url);
            this.scrollMessagesToBottom();
            void this.ensureMessageTranslations(groupChannel.url, [message]);
          }
        },
        onMessageUpdated: (channel, message) => {
          const groupChannel = channel as GroupChannel;
          this.channels.update(existingChannels => this.normalizeChannels(this.upsertChannel(existingChannels, groupChannel)));

          if (this.selectedChannel()?.url === groupChannel.url) {
            this.selectedChannel.set(groupChannel);
            this.messages.update(existingMessages => this.upsertMessage(existingMessages, message));
          }
        },
        onMessageDeleted: (channel, messageId) => {
          const groupChannel = channel as GroupChannel;
          this.channels.update(existingChannels => this.normalizeChannels(this.upsertChannel(existingChannels, groupChannel)));

          if (this.selectedChannel()?.url === groupChannel.url) {
            this.selectedChannel.set(groupChannel);
            this.messages.update(existingMessages => existingMessages.filter(message => message.messageId !== messageId));
          }
        },
        onTypingStatusUpdated: channel => {
          const groupChannel = channel as GroupChannel;

          if (this.selectedChannel()?.url === groupChannel.url) {
            this.selectedChannel.set(groupChannel);
            this.updateTypingUsers(groupChannel);
          }
        },
        onUserMarkedRead: channel => {
          const groupChannel = channel as GroupChannel;
          this.channels.update(existingChannels => this.normalizeChannels(this.upsertChannel(existingChannels, groupChannel)));

          if (this.selectedChannel()?.url === groupChannel.url) {
            this.selectedChannel.set(groupChannel);
          }
        },
      }),
    );

    this.hasRealtimeHandler = true;
  }

  private resolveSelectedChannel(channels: GroupChannel[]): GroupChannel | null {
    const currentUrl = this.selectedChannel()?.url;
    const availableChannels = this.normalizeChannels(channels);

    if (!currentUrl) {
      return availableChannels[0] ?? null;
    }

    return availableChannels.find(channel => channel.url === currentUrl) ?? availableChannels[0] ?? null;
  }

  private findChannelByMember(channels: GroupChannel[], memberId: string): GroupChannel | null {
    return this.normalizeChannels(channels)
      .find(channel => this.otherMember(channel)?.userId === memberId) ?? null;
  }

  private otherMember(channel: GroupChannel | null): Member | null {
    if (!channel) {
      return null;
    }

    const currentUserId = this.currentUserId;

    if (!currentUserId) {
      return channel.members[0] ?? null;
    }

    return channel.members.find(member => member.userId !== currentUserId) ?? channel.members[0] ?? null;
  }

  private sortChannels(channels: GroupChannel[]): GroupChannel[] {
    return [...channels].sort((left, right) => this.channelTimestamp(right) - this.channelTimestamp(left));
  }

  private normalizeChannels(channels: GroupChannel[]): GroupChannel[] {
    return this.sortChannels(channels.filter(channel => this.isMessageableChannel(channel)));
  }

  private isMessageableChannel(channel: GroupChannel): boolean {
    const currentUserId = this.currentUserId;

    if (!currentUserId) {
      return true;
    }

    return channel.members.some(member => member.userId && member.userId !== currentUserId);
  }

  private upsertChannel(channels: GroupChannel[], channel: GroupChannel): GroupChannel[] {
    const nextChannels = new Map(channels.map(existingChannel => [existingChannel.url, existingChannel]));
    nextChannels.set(channel.url, channel);
    return Array.from(nextChannels.values());
  }

  private upsertMessage(messages: BaseMessage[], message: BaseMessage): BaseMessage[] {
    const nextMessageDetails = this.messageDetails(message);
    const nextMessages = [...messages];
    const existingIndex = nextMessages.findIndex(existingMessage => {
      const existingMessageDetails = this.messageDetails(existingMessage);

      return (
        (message.messageId > 0 && existingMessage.messageId === message.messageId)
        || (!!nextMessageDetails.reqId && existingMessageDetails.reqId === nextMessageDetails.reqId)
      );
    });

    if (existingIndex >= 0) {
      nextMessages[existingIndex] = message;
    } else {
      nextMessages.push(message);
    }

    return nextMessages.sort((left, right) => left.createdAt - right.createdAt);
  }

  private async loadRecipientChatLanguage(channel: GroupChannel, version: number): Promise<void> {
    const otherMember = this.otherMember(channel);

    if (!otherMember?.userId || otherMember.userId === this.currentUserId) {
      this.recipientChatLanguage.set(null);
      return;
    }

    try {
      const otherUser = await firstValueFrom(this.userService.getUser(otherMember.userId));
      if (version !== this.messageLoadVersion || this.selectedChannel()?.url !== channel.url) {
        return;
      }

      this.recipientChatLanguage.set(this.normalizeLanguage(otherUser.preferredChatLanguage));
    } catch (error) {
      console.error('Failed to load recipient chat language.', error);

      if (version === this.messageLoadVersion && this.selectedChannel()?.url === channel.url) {
        this.recipientChatLanguage.set(null);
      }
    }
  }

  private async ensureMessageTranslations(channelUrl: string, messages: BaseMessage[]): Promise<void> {
    const preferredLanguage = this.currentUserPreferredChatLanguage;
    if (!preferredLanguage) {
      return;
    }

    const translationTasks = messages
      .filter(message => this.shouldTranslateMessage(channelUrl, message, preferredLanguage))
      .map(async message => {
        if (!message.isUserMessage()) {
          return;
        }

        const requestKey = this.translationRequestKey(channelUrl, message, preferredLanguage);
        this.translationRequestKeys.add(requestKey);

        try {
          const translatedMessage = await this.sbService.translateUserMessage(channelUrl, message, preferredLanguage);

          if (this.selectedChannel()?.url === channelUrl) {
            this.messages.update(existingMessages => this.upsertMessage(existingMessages, translatedMessage));
          }
        } catch (error) {
          console.error('Failed to translate chat message.', {
            channelUrl,
            messageId: message.messageId,
            preferredLanguage,
            error,
          });
        } finally {
          this.translationRequestKeys.delete(requestKey);
        }
      });

    await Promise.allSettled(translationTasks);
  }

  private shouldTranslateMessage(channelUrl: string, message: BaseMessage, preferredLanguage: string): boolean {
    if (this.isOwnMessage(message) || !message.isUserMessage()) {
      return false;
    }

    if (this.messageTranslation(message, preferredLanguage)) {
      return false;
    }

    return !this.translationRequestKeys.has(
      this.translationRequestKey(channelUrl, message, preferredLanguage),
    );
  }

  private shouldShowOriginalMessage(message: BaseMessage): boolean {
    if (this.isOwnMessage(message) || !this.messageTranslation(message)) {
      return true;
    }

    const mode = this.translationDisplayModes()[this.messageKey(message)];
    if (mode) {
      return mode === 'original';
    }

    return this.currentUserPrefersOriginalText;
  }

  private messageTranslation(message: BaseMessage, preferredLanguage = this.currentUserPreferredChatLanguage): string | null {
    if (!preferredLanguage || this.isOwnMessage(message) || !message.isUserMessage()) {
      return null;
    }

    const translations = message.translations as Record<string, unknown> | null | undefined;
    if (!translations) {
      return null;
    }

    const translatedText = translations[preferredLanguage];
    return typeof translatedText === 'string' && translatedText.trim().length > 0
      ? translatedText.trim()
      : null;
  }

  private translationRequestKey(channelUrl: string, message: BaseMessage, preferredLanguage: string): string {
    return `${channelUrl}:${this.messageKey(message)}:${preferredLanguage}`;
  }

  private messageKey(message: BaseMessage): string {
    if (message.messageId > 0) {
      return String(message.messageId);
    }

    return this.messageDetails(message).reqId
      ?? `${message.createdAt}:${this.messageDetails(message).sender?.userId ?? 'unknown'}`;
  }

  private initials(value: string): string {
    const trimmedValue = value.trim();

    if (!trimmedValue) {
      return 'KO';
    }

    const parts = trimmedValue.split(/\s+/).filter(Boolean).slice(0, 2);
    return parts.map(part => part[0]?.toUpperCase() ?? '').join('') || trimmedValue.slice(0, 2).toUpperCase();
  }

  private messageDetails(message: BaseMessage): ChatMessageDetails {
    return message as ChatMessageDetails;
  }

  private revokeImagePreviews(images: PendingChatImage[]): void {
    for (const image of images) {
      URL.revokeObjectURL(image.previewUrl);
    }
  }

  private clearSelectedImages(): void {
    const selectedImages = this.selectedImages();

    if (selectedImages.length > 0) {
      this.revokeImagePreviews(selectedImages);
    }

    this.selectedImages.set([]);
    this.imageError.set(null);
  }

  private resolveStarterDraft(starterType: string | null, projectName: string | null): string | null {
    if (starterType !== 'project-owner' || !projectName?.trim()) {
      return null;
    }

    return `Hi, I'm reaching out about "${projectName.trim()}" on KickOff. I'd love to learn more and see how I can help.`;
  }

  private applyRouteStarter(starterDraft: string | null, contextLabel: string | null): void {
    if (starterDraft) {
      this.draftMessage = starterDraft;
      this.autoGeneratedDraft = starterDraft;
      this.starterContextLabel.set(contextLabel?.trim() || null);
      return;
    }

    this.starterContextLabel.set(null);

    if (this.autoGeneratedDraft && this.draftMessage.trim() === this.autoGeneratedDraft.trim()) {
      this.draftMessage = '';
    }

    this.autoGeneratedDraft = null;
  }

  private clearStarterContext(): void {
    this.starterContextLabel.set(null);
    this.autoGeneratedDraft = null;
  }

  private updateTypingUsers(channel: GroupChannel): void {
    const activeTypingUsers = channel
      .getTypingUsers()
      .filter(member => member.userId && member.userId !== this.currentUserId);

    this.typingUsers.set(activeTypingUsers);
  }

  private async signalTyping(channelUrl: string): Promise<void> {
    if (this.typingChannelUrl !== channelUrl) {
      await this.stopTypingIndicator(this.typingChannelUrl);
    }

    this.typingChannelUrl = channelUrl;

    if (!this.hasActiveTypingSignal) {
      this.hasActiveTypingSignal = true;
      await this.sbService.startTyping(channelUrl);
    }

    if (this.typingTimeoutId) {
      clearTimeout(this.typingTimeoutId);
    }

    this.typingTimeoutId = setTimeout(() => {
      void this.stopTypingIndicator(channelUrl);
    }, 2500);
  }

  private async stopTypingIndicator(channelUrl: string | null = this.typingChannelUrl): Promise<void> {
    if (this.typingTimeoutId) {
      clearTimeout(this.typingTimeoutId);
      this.typingTimeoutId = null;
    }

    if (!this.hasActiveTypingSignal || !channelUrl) {
      this.hasActiveTypingSignal = false;
      this.typingChannelUrl = null;
      return;
    }

    this.hasActiveTypingSignal = false;
    this.typingChannelUrl = null;

    try {
      await this.sbService.endTyping(channelUrl);
    } catch (error) {
      console.error('Failed to clear typing state.', error);
    }
  }

  private isLatestOwnMessage(message: BaseMessage): boolean {
    for (let index = this.messages().length - 1; index >= 0; index--) {
      const currentMessage = this.messages()[index];

      if (!this.isOwnMessage(currentMessage)) {
        continue;
      }

      return currentMessage.messageId === message.messageId;
    }

    return false;
  }

  private formatLastSeen(timestamp: number): string {
    const now = Date.now();
    const elapsedMinutes = Math.max(1, Math.round((now - timestamp) / 60000));

    if (elapsedMinutes < 60) {
      return `${elapsedMinutes}m ago`;
    }

    if (elapsedMinutes < 24 * 60) {
      return `${Math.round(elapsedMinutes / 60)}h ago`;
    }

    return this.timeFormatter.format(timestamp);
  }

  private get currentUserPreferredLanguages(): string[] {
    return this.currentUserPreferredChatLanguage
      ? [this.currentUserPreferredChatLanguage]
      : [];
  }

  private get currentUserPrefersOriginalText(): boolean {
    return this.authState.currentUser()?.showOriginalChatTextByDefault ?? false;
  }

  private get translationTargetLanguages(): string[] {
    const recipientLanguage = this.recipientChatLanguage();
    if (!recipientLanguage || recipientLanguage === this.currentUserPreferredChatLanguage) {
      return [];
    }

    return [recipientLanguage];
  }

  private chatLanguageLabel(language: string | null): string | null {
    switch (language) {
      case 'de':
        return 'German';
      case 'en':
        return 'English';
      case 'es':
        return 'Spanish';
      case 'fr':
        return 'French';
      case 'it':
        return 'Italian';
      case 'ja':
        return 'Japanese';
      case 'ko':
        return 'Korean';
      case 'pt':
        return 'Portuguese';
      case 'ru':
        return 'Russian';
      case 'zh':
        return 'Chinese';
      default:
        return null;
    }
  }

  private normalizeLanguage(language: string | null | undefined): string | null {
    const normalizedLanguage = language?.trim().toLowerCase();
    return normalizedLanguage
      ? normalizedLanguage
      : null;
  }

  private memberPresence(member: Member | null): string {
    if (!member) {
      return 'Offline';
    }

    if (member.connectionStatus === UserOnlineState.ONLINE) {
      return 'Online';
    }

    if (member.lastSeenAt && member.lastSeenAt > 0) {
      return `Last seen ${this.formatLastSeen(member.lastSeenAt)}`;
    }

    return 'Offline';
  }

  private isMemberLive(member: Member | null): boolean {
    return member?.connectionStatus === UserOnlineState.ONLINE;
  }

  private scrollMessagesToBottom(): void {
    requestAnimationFrame(() => {
      const messageList = this.messageListRef?.nativeElement;

      if (!messageList) {
        return;
      }

      messageList.scrollTop = messageList.scrollHeight;
    });
  }

  private resetChatState(): void {
    this.clearSelectedImages();
    this.channels.set([]);
    this.selectedChannel.set(null);
    this.messages.set([]);
    this.recipientChatLanguage.set(null);
    this.translationDisplayModes.set({});
    this.translationRequestKeys.clear();
    this.typingUsers.set([]);
  }
}
